const { DAILY_LIMIT_TEXT, MIN_WITHDRAW, BONUS_THRESHOLD, BONUS_AMOUNT } = require('./constants');

const texts = {
  fa: {
    chooseLanguage: 'زبان خود را انتخاب کنید / Please choose your language:',
    welcome: 'به خانواده‌ی ما خوش اومدی! 🌟',
    requestPhone: 'برای تکمیل ثبت‌نام، لطفاً شماره تلفن خود را با دکمه‌ی زیر ارسال کنید 👇',
    sharePhoneButton: '📱 ارسال شماره تلفن',
    requestName: 'لطفاً نام و نام خانوادگی خود را وارد کنید:',
    requestCard: 'لطفاً شماره کارت بانکی خود را وارد کنید:',
    rulesText: 'قوانین و شرایط استفاده:\n\n(متن قوانین بعداً از پنل مدیریت تکمیل می‌شود)',
    confirmRulesButton: '✅ قوانین را می‌پذیرم',
    registrationSuccess: '🎉 ثبت‌نام شما با موفقیت انجام شد!',
    welcomeBack: 'خوش برگشتی! 👋',
    walletTitle: '🎒 جیب',
    walletBalance: '💰 موجودی فعلی شما: ',
    walletIncrease: '➕ افزایش موجودی',
    walletWithdraw: '💳 برداشت موجودی',
    walletAddCard: '➕ افزودن کارت جدید',
    backButton: '🔙 بازگشت',
    depositMethodTitle: 'روش افزایش موجودی را انتخاب کنید:',
    depositCard2Card: '💳 کارت به کارت',
    depositTron: '🪙 ترون (تتر)',
    depositGateway: '🌐 درگاه پرداخت',
    comingSoon: 'به‌زودی 🙂',
    depositCardsTrust: '✅ پرداخت شما مستقیماً به حساب رسمی مجموعه واریز می‌شود.',
    depositAskAmount: 'مبلغ واریزی خود را به تومان وارد کنید:',
    depositAskReceipt: 'رسید (فیش) پرداخت خود را همینجا ارسال کنید 📎',
    depositSubmitted: 'درخواست شارژ شما ثبت شد ✅',
    withdrawAskAmount: 'مبلغ برداشت خود را به تومان وارد کنید (حداقل ' + MIN_WITHDRAW.toLocaleString('en-US') + ' تومان):',
    withdrawMinError: 'حداقل مبلغ برداشت ' + MIN_WITHDRAW.toLocaleString('en-US') + ' تومان است.',
    withdrawSelectCard: 'شماره کارت خود را انتخاب کنید:',
    withdrawSubmitted: 'درخواست برداشت شما ثبت شد ✅',
    addCardAsk: 'شماره کارت جدید را وارد کنید (۱۶ رقم):',
    addCardInvalid: 'شماره کارت وارد شده معتبر نیست.',
    addCardSuccess: 'کارت جدید با موفقیت ثبت شد ✅',
    addCardButton: '➕ افزودن کارت جدید',
    buyMenuTitle: '✨ کدوم محصول رو می‌خوای بخری؟',
    buyNoProducts: 'فعلاً هیچ محصولی برای فروش تعریف نشده.',
    buyAskAmountUsd: '💵 قیمت هر دلار: {rate} تومان\n💰 حداقل خرید: {minUsd} دلار',
    buyAskAmountToman: '💰 حداقل خرید: {min} تومان',
    buyMinError: 'مبلغ واردشده کمتر از حداقل خرید ({min} تومان) است.',
    buyMaxError: 'مبلغ واردشده بیشتر از حداکثر خرید ({max} تومان) است.',
    buyConfirmSummary: '📦 خلاصه‌ی سفارش:\n\nمحصول: {product}\nمبلغ: {amount} تومان',
    buyConfirmButton: '✅ تایید و خرید',
    buyCancelButton: '❌ انصراف',
    buySuccess: '🎉 خرید شما با موفقیت انجام شد!',
    buySuccessPending: '✅ سفارش شما ثبت شد!',
    buyInsufficientBalance: '❌ موجودی کیف پولت کافی نیست.',
    buyChargeWalletButton: '💳 شارژ کیف پول',
    buyCancelled: 'سفارش لغو شد.',
    profileTitle: '👤 پروفایل شما',
    invoicesTitle: '🧾 فاکتورهای من',
    invoicesEmpty: 'هنوز هیچ فاکتوری برای شما ثبت نشده.',
    supportTitle: '📞 پشتیبانی',
    supportFaqButton: '❓ سوالات متداول',
    supportContactButton: '💬 ارتباط با پشتیبانی',
    supportContactText: 'برای ارتباط مستقیم با پشتیبانی، پیام خودتون رو همینجا بنویسید.',
    faqText: '❓ سوالات متداول',
    gameMenuTitle: '🎮 بازی و بونوس',
    gameNotEligible: '🔒 هنوز بونوس بازی برات فعال نشده.',
    gameEligibleIntro: '🎁 تبریک! یه بونوس داری.',
    gameAlreadyUsed: 'بونوس بازیت رو قبلاً استفاده کردی.',
    gameDiceButton: '🎲 بازی تاس',
    gameBasketballButton: '🏀 بازی بسکتبال',
    gamePlaying: '🎲 در حال بازی...',
    gameWin: '🎉🎉 تبریک، بردی!!',
    gameLose: '😔 این بار نبردی.',
    sellMenuTitle: '✨ کدوم محصول رو می‌خوای بفروشی؟',
    sellNoProducts: 'فعلاً هیچ محصولی برای خرید از شما تعریف نشده.',
    sellAskCode: '💸 فروش {product}\n\n♻️ قیمت واحد: {price} تومان\n\n🎫 نمونه کد صحیح:\n{sample}',
    sellCodeReceived: '✅ کد شما دریافت شد.',
    sellApprovedUser: '✅ فروش شما تایید شد.',
    sellRejectedUser: '❌ درخواست فروش شما رد شد.',
    sellAskFinalAmount: '💰 مبلغ نهایی رو به تومان وارد کنید:'
  }
};

module.exports = texts;
